### ISSUE TITLE
Debug npm sometimes failing build

### ISSUE THREAD

**Issue by DavidLu1997** [DavidLu1997/gogogo#43]

**Comment by Denton-L** [comment]
Seems to be an issue with Travis CI having a dirty instance. Sometimes, there's a lock even though we're starting a fresh build instance.

Workaround for now is just restarting the build.

**Comment by Denton-L** [comment]
Can confirm, this is [not our problem](https://www.traviscistatus.com/incidents/2p40l49r3yxd).

Would recommend closing.
