### ISSUE TITLE
Proposal: Name of Organization

### ISSUE THREAD

**Issue by DavidLu1997** [DavidLu1997/gogogo#48]
Let's switch away from copyright me and having the repo under my account.

Taking all suggestions for a GitHub organization name

**Comment by Denton-L** [comment]
Seki Software?

**Comment by ian952** [comment]
SekiSoft

**Comment by AnmolMago** [comment]
2Soft2seki

**Comment by Denton-L** [comment]
Can we have a vote on which potential name to go with? The one with the most hearts by Monday is our name?

@tiffanynwyeung, post your thing here.

**Comment by Denton-L** [comment]
FalseTech Innovations

**Comment by DavidLu1997** [comment]
TaylorHard

**Comment by Denton-L** [comment]
Shallow Blue

**Comment by tiffanynwyeung** [comment]
Sigma Innovations because bright (dank) minds think alike

**Comment by Denton-L** [comment]
It is decided, we are now SEkiSoft!
