### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by R-Wang97** [DavidLu1997/gogogo#78]
Right now the build is missing a step that may cause build errors. Will add it to the README.md. Also add a section for troubleshooting various build errors

**Comment by Denton-L** [comment]
Not an issue, users are supposed to `git clone --recursive` instead of `git clone`, normally. Would recommend closing.

**Comment by R-Wang97** [comment]
I'm referring to the error where it can't find log4go, does `--recursive` fix that?

**Comment by Denton-L** [comment]
It should, yes. Or `git submodule update --init`.
